apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduly
spec:
  replicas: 1
  selector:
    matchLabels:
      name: scheduly
  template:
    metadata:
      labels:
        name: scheduly
        version: "1.0.0"
    spec:
      containers:
        - name: scheduly
          image: molynx/scheduly:1.0.0-SNAPSHOT
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_USERNAME # Name of the environment variable
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: password
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://mysql:3306/mysql?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
            - name: MYSQL_HOST
              value: mysql
            - name: MYSQL_DATABASE
              value: mysql
            - name: APPLICATION_PORT
              value: "8080"
            - name: DB_HOST
              value: mysql
            - name: DB_NAME
              value: mysql
            - name: DB_PASSWORD
              value: password
            - name: DB_PORT
              value: "3306"
            - name: DB_USER
              value: root
            - name: SPRING_DATA_MONGODB_HOST
              value: mongodb-service
            - name: SPRING_DATA_MONGODB_PORT
              value: "27017"
            - name: SPRING_DATA_MONGODB_DATABASE
              value: mongo
            - name: SPRING_DATA_MONGODB_AUTHENTICATION-DATABASE
              value: admin
            - name: SPRING_DATA_MONGODB_USERNAME
              value: root
            - name: SPRING_DATA_MONGODB_PASSWORD
              value: password
---
apiVersion: v1
kind: Service
metadata:
  name: scheduly
  labels:
    name: scheduly
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    name: scheduly
    version: "1.0.0"
  type: LoadBalancer
