apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduly
spec:
  replicas: 1
  selector:
    matchLabels:
      name: scheduly
  template:
    metadata:
      labels:
        name: scheduly
        version: "1.0.0"
    spec:
      containers:
        - name: scheduly
          image: molynx/scheduly:0.0.1-SNAPSHOT
          ports:
            - name: http
              containerPort: 8080
          
---
apiVersion: v1
kind: Service
metadata:
  name: scheduly
  labels:
    name: scheduly
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    name: scheduly
    version: "1.0.0"
  type: LoadBalancer
